---
  - name: Add APT key
    become: true
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-3.2.asc
      state: present
    tags: install

  # Подключаем репу монги
  - name: Add APT repository
    become: true
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
      update_cache: yes
    tags: install

  # Выполним установку монги
  - name: Install mongodb
    become: true
    apt:
      name: mongodb-org
      state: present
    tags: install

  # Энейблим монгу
  - name: systemctl enable mongod
    become: true
    systemd:
      name: mongod
      enabled: yes
      state: started
    tags: install
...
