---
- name: deploy app
  hosts: app
  vars:
    deploy_user: decapapreta
  tasks:
    - name: fetch latest version of app
      become: true
      git:
        repo: 'https://github.com/express42/reddit.git' # repo
        dest: "/home/{{deploy_user}}/reddit"
        version: monolith # branch_name
      notify: reload puma

    - name: bundle install
      bundler:
        state: present
        chdir: "/home/{{deploy_user}}/reddit"

  handlers: # <-- Добавим блок handlers и задачу
    - name: reload puma
      become: true
      systemd: name=puma state=restarted
...
