---
- name: deploy app
  hosts: app
  tasks:
    - name: fetch latest version of app
      git:
        repo: 'https://github.com/express42/reddit.git' # repo
        dest: /home/decapapreta/reddit
        version: monolith # branch_name
      notify: reload puma

    - name: bundle install
      bundler: 
        state: present
        chdir: /home/decapapreta/reddit
      
  handlers: # <-- Добавим блок handlers и задачу
    - name: reload puma
      become: true
      systemd: name=puma state=restarted
... 
